/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get posts feed
     * @description Paginated list of posts sorted by createdAt desc. Paid posts have empty body.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of posts (max 20) */
          limit?: number;
          /** @description ID of the last received post */
          cursor?: string;
          /** @description Filter by tier: free or paid */
          tier?: 'free' | 'paid';
          /** @description Return 500 for error handling testing */
          simulate_error?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Posts list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostsResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        500: components['responses']['InternalError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get post by ID
     * @description Full post details. Paid posts have empty body.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example post_1 */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Post detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostDetailResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}/like': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Toggle like
     * @description Like/unlike a post (toggle). Triggers a like_updated WebSocket event after 1-3s delay.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example post_1 */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Like toggled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LikeResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get comments
     * @description Paginated list of comments for a post.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of comments */
          limit?: number;
          /** @description Cursor for pagination */
          cursor?: string;
        };
        header?: never;
        path: {
          /** @example post_1 */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Comments list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommentsResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    /**
     * Add comment
     * @description Create a new comment. Triggers a comment_added WebSocket event.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example post_1 */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @example Отличный пост! */
            text: string;
          };
        };
      };
      responses: {
        /** @description Comment created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommentCreatedResponse'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Author: {
      /** @example author_1 */
      id?: string;
      /** @example lesha_krid */
      username?: string;
      /** @example Леша Крид */
      displayName?: string;
      /**
       * Format: uri
       * @example https://i.pravatar.cc/150?u=author_1
       */
      avatarUrl?: string;
      /** @example Музыка, визуальное искусство и эксперименты. */
      bio?: string;
      /** @example 1420 */
      subscribersCount?: number;
      /** @example true */
      isVerified?: boolean;
    };
    Post: {
      /** @example post_1 */
      id: string;
      author?: components['schemas']['Author'];
      /** @example Подготовка к лету */
      title?: string;
      /** @description Full text. Empty string for paid posts. */
      body?: string;
      /** @description Short preview up to 120 chars */
      preview?: string;
      /**
       * Format: uri
       * @example https://picsum.photos/seed/post_1/800/450
       */
      coverUrl?: string;
      /** @example 248 */
      likesCount?: number;
      /** @example 17 */
      commentsCount?: number;
      /** @description Whether current user liked this post */
      isLiked?: boolean;
      /** @enum {string} */
      tier?: 'free' | 'paid';
      /** Format: date-time */
      createdAt: string;
    };
    Comment: {
      /** @example comment_1 */
      id?: string;
      /** @example post_1 */
      postId?: string;
      author?: components['schemas']['Author'];
      /** @example Очень круто, ждём продолжения! */
      text?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    PostsResponse: {
      /** @example true */
      ok?: boolean;
      data?: {
        posts?: components['schemas']['Post'][];
        /** @example post_10 */
        nextCursor?: string | null;
        hasMore?: boolean;
      };
    };
    PostDetailResponse: {
      /** @example true */
      ok?: boolean;
      data?: {
        post?: components['schemas']['Post'];
      };
    };
    LikeResponse: {
      /** @example true */
      ok?: boolean;
      data?: {
        isLiked?: boolean;
        likesCount?: number;
      };
    };
    CommentsResponse: {
      /** @example true */
      ok?: boolean;
      data?: {
        comments?: components['schemas']['Comment'][];
        nextCursor?: string | null;
        hasMore?: boolean;
      };
    };
    CommentCreatedResponse: {
      /** @example true */
      ok?: boolean;
      data?: {
        comment?: components['schemas']['Comment'];
      };
    };
    ErrorResponse: {
      /** @example false */
      ok?: boolean;
      error?: {
        /** @example NOT_FOUND */
        code?: string;
        /** @example Post not found */
        message?: string;
      };
    };
  };
  responses: {
    /** @description Invalid or missing UUID token */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Request body validation failed */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Internal server error */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
